---

- name: "Instalando os pacotes do Git no {{ ansible_distribution }}"
  when: ansible_os_family | lower == "debian"
  apt:
    name: "git"
    state: present
    update_cache: yes
  tags:
    - git
    - git_install


- name: "Instalando pacotes do Git no {{ ansible_distribution }}"
  when: ansible_distribution | lower == "fedora"
  dnf:
    name: "git"
    state: present
    disable_gpg_check: yes
  tags:
    - git
    - git_install


- name: "Instalando pacotes do Git no SUSE ou OpenSUSE"
  when: ansible_os_family | lower == "suse"
  zypper:
    name: "git"
    state: latest
    force: yes
  tags:
    - git
    - git_install